name: Requirements Generator
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all
    
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Self test
        id: selftest

        uses: ryan-rozario/pipreqs-action-cpy@master

        with:
          PROJECT_PATH: "." #default is the root of the repository
          REQUIREMENT_PATH: "requirements.txt" #default is requirement.txt in the root of your repository